import "./globals.css";

export const metadata = {
  icons : "./next.svg",
  title: "Simple Project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
